require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/rails_db_analytics/version.rb'

# Rails-specific configuration
Rails:
  Enabled: true

# Style Configurations
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

# Layout Configurations
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  Enabled: true

# Metrics Configurations
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - '**/*.gemspec'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'

# RSpec-specific configurations
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

# Performance Configurations
# Performance/AncestorsInclude:
#   Enabled: true

# Performance/BigDecimalWithNumericArgument:
#   Enabled: true

# Performance/RedundantSortBlock:
#   Enabled: true

# Performance/ReverseFirst:
#   Enabled: true

# Performance/SortReverse:
#   Enabled: true

# Performance/Squeeze:
#   Enabled: true

# Performance/StringReplacement:
#   Enabled: true

# Security Configurations
Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

# Naming Configurations
Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: true
  ForbiddenPrefixes:
    - is_
    - have_

# Bundler-specific configurations
Bundler/OrderedGems:
  Enabled: false
